import{a as h,S as b,i as d}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const L="47394057-a123a8d6d5d39dc35fe9d8ef3",v="https://pixabay.com/api/";async function m(e,r=1,i=15){const a={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i};try{return(await h.get(v,{params:a})).data}catch(t){throw console.error("Error fetching images:",t.message),t}}function E(e){return e.map(({webformatURL:r,largeImageURL:i,tags:a,likes:t,views:o,comments:l,downloads:g})=>`
    <a href="${i}" class="gallery-item">
      <div class="photo-card">
        <img src="${r}" alt="${a}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b> ${t}</p>
          <p class="info-item"><b>Views</b> ${o}</p>
          <p class="info-item"><b>Comments</b> ${l}</p>
          <p class="info-item"><b>Downloads</b> ${g}</p>
        </div>
      </div>
    </a>
  `).join("")}function w(e){e.innerHTML=""}const S=document.querySelector("#search-form"),u=document.querySelector(".gallery"),$=document.querySelector(".loader"),s=document.createElement("button");s.textContent="Load more";s.classList.add("load-more");s.style.display="none";u.after(s);let y=new b(".gallery a"),c="",f=1;S.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.searchQuery.value.trim(),!c){d.error({title:"Error",message:"Please enter a search term!"});return}e.target.elements.searchQuery.value="",w(u),f=1,n(!0),s.style.display="none";try{const r=await m(c,f);if(n(!1),r.hits.length===0){d.error({message:`Sorry, no images found for "${c}". Please try again!`});return}p(r.hits),y.refresh(),r.totalHits>r.hits.length&&(s.style.display="block")}catch(r){n(!1),d.error({title:"Error",message:r.message})}});s.addEventListener("click",async()=>{f+=1,n(!0);try{const e=await m(c,f);n(!1),p(e.hits),y.refresh(),P(),f*15>=e.totalHits&&(s.style.display="none",d.info({message:"We're sorry, but you've reached the end of search results."}))}catch(e){n(!1),d.error({title:"Error",message:e.message})}});function n(e){$.style.display=e?"block":"none"}function p(e){const r=E(e);u.insertAdjacentHTML("beforeend",r)}function P(){const{height:e}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*1,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
